# Static lists for lookups
ERP_SYSTEMS = [
    "3L", "ABILA MIP", "AccountingSeed", "Accountview", "Acumatica", "Å-Data", "Adept", 
    "Aderant", "Aditro", "Advanced", "Advantage", "AFAS Online", "Agilysys", "Agresso", 
    "Agro-IT", "AMS360", "Apparel21", "Aptean Ross ERP", "ApTech PVNG", "Aptos", "AS/400", 
    "Aspect4", "Aspen", "Autoline", "Automate 9.2", "Avanti", "Avantix", "Aveny", "Axiom", 
    "Baan", "Balans", "BankTel", "Banner", "Basware", "Bespoke", "Bison", "BL Administration", 
    "BlueBee", "Blue Cherry", "BPCS", "Bravo", "Briljant", "Bryne Software", "Builder 360", 
    "Capita eSeries", "Capita Integra", "CargoWise", "Catapult", "CDK", "Cegeka BE", "Cegeka NL", 
    "CivicView", "Club Essentials", "CMI", "CMIC", "COA", "Coins", "COINS OA", "Compeat", 
    "Computerease", "Computron", "Conactivity", "Construction Industry Solutions (COINS)", 
    "Copernicus", "CPSI", "Crom", "Cura", "Curtis Fitch", "Custom ERP", "DataBuild", "Data Plus", 
    "Deacom", "Deltek Ajera", "Deltek Vision", "Didata", "Divalto", "Domain6", "DSMI Agility", 
    "E-conomic", "Edison", "eFinancials (ABS)", "eGlobal", "Elite", "Ellucian Banner", "Encompix", 
    "Encore Business Solutions", "Enertia", "Enfinium", "Enrich", "Entre", "EO Star", "ePass", 
    "EPIC", "Epicor", "Epicor 9", "Epicor iScala", "Equip", "ERP Not Listed", "eSeries", 
    "Euro dossier", "Exact Financials", "Exact Globe", "Exact Online", "Fackta", "FAMIS", 
    "Famous ERP", "FDT", "Fenix", "Financial Force", "Formula", "Fortnox", "Friedman", "Frontier", 
    "FTL", "Full Circle", "Garp", "Global Edge", "GRMS", "Hansaworld", "Hitachi", "Hogia", "HP", 
    "Growth Point", "IBM", "IBM AS400", "IBS Enterprise / ASW", "IFS", "Incit Xpand", 
    "Infor(Adage)", "Infor FMS", "Infor Infinium", "Infor LN (Baan)", "Infor LX", "Infor M3", 
    "Infor M3 Multi-Tenant Cloud", "Infor M3 Single Tenant Cloud", "Infor S3", "Infor SunSystems", 
    "Infor SX", "Infor System21", "Infor SyteLine", "Infor Visual", "Infor XA", "Infosync", 
    "Integrow", "Intellidealer", "Iptor DC-1", "Iptor IP1 (IBS Bookmaster)", "ISS", "JAMIS Prime", 
    "JBA", "Jeeves", "jenzabar", "Jobscope", "Jonas", "Jonas Software", "KBM (Knowledge Based Manufacturing)", 
    "Kerridge", "King", "Kobra", "Kyriba", "Lawson", "Lennox", "LIMS", "Lumbertrack", "Maconomy", 
    "Mac-Pac", "Madden Co", "Made2Manage", "Magic", "Mammut", "Mapics", "Marathon", "Marcam A/P w AS400", 
    "MAS 200", "Maximo", "McCloud Transportation Software", "McKesson", "McLeod", "Meditech", 
    "MediusGo Pay", "Medius Payment Output", "MFG/PRO", "Microsoft Navision", "Microsoft Platinum", 
    "Mincom", "Mining ERP", "Mincron", "MomentumPro", "Monitor", "Motility", "Movex", "MRI", 
    "MS Dynamics", "MS Dynamics 365 Business Central", "MS Dynamics 365 for Fi&Op", "MS Dynamics AX", 
    "MS Dynamics C5", "MS Dynamics GP", "MS Dynamics NAV", "MS Dynamics SL", "MS Dynamics XAL", 
    "MultiPlus", "Multi-View", "Munis", "MXP", "N/A", "Navision", "NCR", "NEP", 
    "New Tribes Mission ERP", "Nexsyis", "No ERP Integration", "Northstar", "Octal", "Odoo", 
    "OneSite Accounting", "OpenCube Technologies", "Oracle", "Oracle EBS", "Oracle ERP Cloud", 
    "Oracle Fusion", "Oracle JD Edwards", "Oracle JD Edwards EnterpriseOne", "Oracle JD Edwards World", 
    "Oracle NetSuite", "Oracle SBS", "Orion", "OSG", "Other", "PDI Technologies", "Pengvin", 
    "Pentagon", "PeopleSoft", "PHLEX", "PlateIQ", "Platinum ERP", "pp7 ecosoft", "PRMS", "Proactis", 
    "ProfitKey", "Profit Tool / SAP", "Prologue", "Pronto", "Proprietary", "ProVantage", "Pyramid", 
    "QAD", "QAD/MFGPRO", "QB", "QDA / MSG Pro", "Quantum", "QuickBooks", "Quicken", "Raindance", 
    "RealPage", "ResMan", "Respons", "Retalix", "Reveny", "Reynolds & Reynolds", "Rippie & Kingston", 
    "Rootstock", "Rsult", "Rubicon", "Sage", "Sage 100", "Sage 1100", "Sage 200", "Sage 300 ERP", 
    "Sage 50", "Sage 500", "Sage Accpac", "Sage Intacct", "Sage Live", "Sage One", "Sage X3", 
    "SAP", "SAP - Ariba", "SAP Business ByDesign", "SAP BusinessOne", "SAP ByDesign", "SAP S/4 HANA", 
    "SBS", "Sedona", "ShipNet", "Smartstream", "Softbase", "SoftOne Business", "Sonet Premium", 
    "Spectrum R2 (Cloud)", "Spokane FACS", "SSA", "StarBuilder", "Storis", "Strategic Solutions NW", 
    "Styr/400", "Sungaurd", "Sun Systems", "Superion OneSolution", "Swelog", "SX", "Synegetic", 
    "Syspro", "SyteLine", "TechnologyOne", "Tecsys Elite", "Tecsys Streamline", "TELUS", "Timberline", 
    "TMW", "TowBook", "Traverse Open Systems", "TruckMate", "TL2000", "Trygg 2000", "Twinfield", 
    "Unanet", "Undecided/Still Evaluating", "UNIT4", "UNIT4 Agresso", "Unit4 Business World On!", 
    "UNIT4 Coda Financials", "Unknown", "VAI", "Venice", "Vericent", "ViewPoint", "VIP", "Visibility", 
    "Visma.net", "Visma Administration", "Visma Business", "Visma Compact", "Visma Control", 
    "Visma Control Edge", "Visma e-ekonomi", "Visma Global", "Visma Public Business Suite", 
    "Visma PX", "Visma SPCS", "Vista", "Vitec Ekonomi", "Winbas", "Workday", "Xledger", "Xor", 
    "Xpand", "Yardi"
]

INDUSTRIES = [
    "Accounting Services", "Advertising", "Marketing", "Agriculture & Forestry", 
    "Architecture & Engineering", "Automotive", "Banking", "Biotechnology", 
    "Broadcast Media", "Casinos & Gambling", "Chemicals", "Computer Software", 
    "Construction", "Consumer Products", "Defense & Aerospace", "Department Stores", 
    "eCommerce", "Electronics", "Energy / Utilities", "Financial Services", 
    "Food Processing", "Food & beverages", "Gaming Software/Systems", "Government", "Hardware", 
    "Health Insurance", "Higher Education", "Holding Companies", "Hospitals / Health Care", 
    "Insurance", "IT Services", "Legal Services", "Leisure", "Lodging", 
    "Logistics / Transportation", "Manufacturing - Durables", "Manufacturing - Non-Durables", 
    "Medical Devices", "Minerals & Mining", "Non-Profit", "Oil & Gas", "Other", 
    "Pharmaceuticals", "Print & Digital Media", "Professional Services", 
    "Professional Sports", "Real Estate", "Property Management", "Religious Organizations", 
    "Restaurants", "Retail", "School Districts", "Services", "Social Media", 
    "Staffing & Recruiting", "Supermarkets", "Technology", 
    "Telecom / Communication Services", "Travel & Tourism", 
    "Venture Capital & Private Equity", "Waste Management", "Wholesale"
]

PRODUCT_ACTIVATIONS = [
    "Analytics","AP Automation - Archive","AP Automation - Invoice","AP Automation - Match","AP Automation - Prepayments",
    "AP Automation - Recurring","Buy","Capture","Connect API","Connect AX CIG","Connect AX MIG","Connect BC Cloud","Connect BC On-Premise",
    "Connect Fi&Op Cloud","Connect Fi&Op On-Premise","Connect FX","Connect Iptor","Connect M3 Cloud","Connect M3 On-Premise","Connect NAV","Connect Netsuite",
    "Connect SAP CIG","Contract Management","Copilot - AP Automation","Document Approval","E-invoicing API","E-Invoicing General","Expensya expenses",
    "Fraud & Risk detection","Medius Pay","Procurement","Product Activation","Readsoft Invoices","Readsoft Online","Sourcing","Supplier conversations",
    "Supplier Information Management","Supplier Onboarding","Supplier Portal","Supplier Relationship Management"
]